Blog app - Views
username-forGithub/rails_blog_app pull request #6
Opened 2022-12-02 21:20 UTC by username-forGithub

- Use preprocessed HTML file with embedded Ruby code.
- Use layouts and templates for shared content.
- Added partials containing the following information:
_user_info
_post_info
_comment

2022-12-02 21:34 UTC, DammyShittu requested changes
Hi @username-forGithub,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 21:34 UTC, DammyShittu commented on app/views/users/show.html.erb
> +</section>
- [ ] Kindly improve your styling for the user show page. Kindly center your items on the page based on the wireframe.

  See [wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_page.png?token=GHSAT0AAAAAABY4RVENW6H3RCPXJM4QS73IY4KPT6Q)

  ![image](https://user-images.githubusercontent.com/54848363/205391707-ce99a851-7cf1-4e06-b492-9f84b30115a6.png)

2022-12-03 05:34 UTC, username-forGithub commented
Amended. Centered.

2022-12-03 08:13 UTC, arslanbisharat commented
Hi @username-forGithub,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 08:17 UTC, username-forGithub commented
Thank you.
@arslanbisharat  and @DammyShittu

2022-12-03 08:25 UTC, merged